export type Project = {
  title: string;
  src: string | null;
  href: string | null;
  description: string;
  stack: string[];
};

export const projects: Project[] = [
  {
    title: "Swift Aza",
    src: null,
    description:
      "Swift Aza is a simple Crypto Web App. With On-Ramp (Buy Crypto) and Off-Ramp (Sell Crypto) features. Leveraging <a href='https://paybis.com' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>Paybis</a> Apis and Widget Web SDK. While using <a href='https://convex.dev' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>Convex</a> Backend as a Service. And <a href='https://posthog.com' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>PostHog</a> for Analytics.",
    href: "https://swiftaza.com",
    stack: [
      "React",
      "TypeScript",
      "Next JS",
      "Tailwind CSS",
      "Node JS",
      "Shad CN",
      "Git",
      "GitHub",
      "Railway",
      "Convex",
      "Convex Auth",
      "Paybis Apis",
      "Paybis Widget Web SDK",
      "PostHog",
    ],
  },
  {
    title: "Knockout Pokedex",
    src: null,
    description:
      "This is a simple Pokedex built with Knockout.js. In my attempt to learn Knockout.js, I decided to build a simple Pokedex. The Pokedex is a simple web application that displays a list of Pokemon and their details. The application is built with Knockout.js, HTML, CSS, and JavaScript.",
    href: "https://knockout-pokedex.vercel.app",
    stack: [
      "HTML",
      "CSS",
      "JavaScript",
      "Knockout.js",
      "Vite",
      "Git",
      "GitHub",
      "Vercel",
      "Node JS",
      "PokeApi",
    ],
  },
  {
    title: "Triptimizer",
    src: null,
    description:
      "Triptimizer is an innovative web application designed to streamline the process of planning and optimizing your trips. With Triptimizer, you can effortlessly generate the most efficient routes for your journeys, taking into account either the shortest distance or the shortest time to reach multiple destinations.",
    href: "https://triptimizer.com",
    stack: [
      "React",
      "TypeScript",
      "Next JS",
      "CSS Modules",
      "SCSS",
      "Simpler State",
      "React Hook Form",
      "Git",
      "GitHub",
      "Vercel",
      "Node JS",
      "Restful Api",
      "Postman",
      "Vercel KV (a Redis Store)",
      "Google Places Api",
      "Google Distance Matrix Api",
      "Google Sheets Api",
      "Resend",
    ],
  },
  {
    title: "Jochebed Foundation Website",
    src: null,
    description:
      "Official Jochebed Foundation Website. Jochebed Foundation is a non-profit organization that provides education via her scholarship initiative to people regardless of financial barriers. Jochebed Foundation also provides funding for religious projects.",
    href: "https://jochebed-foundation.clearerangle.com",
    stack: [
      "React",
      "TypeScript",
      "Next JS",
      "Tailwind CSS",
      "Shad CN",
      "React Hook Form",
      "Git",
      "GitHub",
      "Vercel",
      "Node JS",
    ],
  },
  {
    title: "Any CBT",
    src: null,
    description:
      "Any CBT allows you generate CBT questions and take a quiz from uploaded materials from written text, uploaded documents and youtube video.",
    href: "https://anycbt.clearerangle.com",
    stack: [
      "React",
      "TypeScript",
      "Next JS",
      "Tailwind CSS",
      "Shad CN",
      "Simpler State",
      "React Hook Form",
      "Git",
      "GitHub",
      "Vercel",
      "Node JS",
      "Restful Api",
      "Postman",
      "Render",
      "Stripe",
      "Resend",
    ],
  },
  {
    title: "Terrace FI",
    src: "https://drive.google.com/uc?id=1p65N23z_0lRwLKWQe6h4Vph2_pTinIm4",
    description:
      "<a href='https://terrace.fi' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>Terrace</a> provides market access to the world’s leading centralized and decentralized crypto trading and liquidity venues through a single, integrated platform. This is a platform similar to Binance but targeted towards businesses rather than individual customers. Even though personal accounts are also supported.",
    href: "https://app.terrace.fi",
    stack: [
      "React",
      "TypeScript",
      "Next JS",
      "Graph QL",
      "Apollo GraphQL Playground",
      "Node JS",
      "Hasura",
      "Tailwind CSS",
      "Shad CN",
      "Fusion Auth",
      "Aphrodite CSS",
      "MOBX",
      "Git",
      "GitHub",
      "AWS",
    ],
  },
  {
    title: "Love Message",
    src: null,
    description:
      "Love Message is a fun project that encrypts and decrypts a message.",
    href: "https://lm.tunjioyeniran.com",
    stack: [
      "React",
      "TypeScript",
      "Next JS",
      "CSS Modules",
      "SCSS",
      "Simpler State",
      "Git",
      "GitHub",
      "Vercel",
    ],
  },
  {
    title: "Yawo",
    src: null,
    description:
      "Yawo is a platform that gives quick loan to small businesses especially traders.",
    href: "https://yawo.ng",
    stack: [
      "React",
      "Next JS",
      "Styled Components",
      "Simpler State",
      "Contentful",
      "Git",
      "GitHub",
      "Netlify",
    ],
  },
  {
    title: "Account Report",
    src: "https://poly-screenshots.wellfound.com/Project/0b/1294367/688b6a8ea2e87b7b91697defe78f91dd-original.png",
    description:
      "Account Report is an accounting software developed to make financial data entry easy & generating financial reports even easier. <a href='https://wellfound.com/projects/1294367-account-report' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>See Screenshots on Wellfound</a>",
    href: null,
    stack: [
      "PHP",
      "TALL STACK",
      "Tailwind CSS",
      "Alpine JS",
      "Laravel 8",
      "Laravel Livewire",
      "Git",
      "Github",
      "CI/CD",
      "Heroku",
    ],
  },
  {
    title: "Reventify App",
    src: "https://poly-screenshots.wellfound.com/Project/cd/1294370/38af80eac1b94bd3109b0a5bbd72d7b8-original.png",
    description:
      "Reventify is a progressive web application that provides professionals with the resources and tools needed to advance their careers. Career planning tool and <b>CV Builder</b> with <b>Expert Insights / Smart Suggestions</b>. Visit <a href='https://reventify.com' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>Reventify Website</a> for more information about features. <a href='https://wellfound.com/projects/1294370-reventify-web-app' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>See Screenshots on Wellfound</a>",
    href: null,
    stack: [
      "React",
      "Redux",
      "Next JS",
      "PWA",
      "Vercel",
      "SCSS",
      "CSS Grid",
      "FIGMA",
      "Git",
      "Github",
      "CI/CD",
      "Node JS",
      "GraphQL Client",
      "Google Cloud Platform (GCP)",
      "Puppeteer // for downloading CV as PDF",
    ],
  },
  {
    title: "Agridata",
    src: "https://poly-screenshots.wellfound.com/Project/ab/1294383/d16f57a63af2ce72e2d9da338ba115d7-original.png",
    description:
      "Agridata by Agriteer. The aim of the project is to create a place for people to get the latest average market price for common day to day commodities such as Beans, Rice etc. <a href='https://wellfound.com/projects/1294383-agridata' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>See Screenshots on Wellfound</a>",
    href: null,
    stack: [
      "PHP",
      "TALL STACK",
      "Tailwind CSS",
      "Alpine JS",
      "Laravel 8",
      "Laravel Livewire",
      "Git",
      "Github",
      "CI/CD",
      "Heroku",
      "Excel Sheet Import",
    ],
  },
  {
    title: "IFSGRANT",
    src: null,
    description:
      "IFSGRANT is an application built for managing forest population data within a region or location. Registered Users can upload statistics generated from field research into the system which will then automatically calculate other statistics using preset formulas. <a href='https://documenter.getpostman.com/view/7841485/TVmJhJTZ' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>IFSGRANT API V1 Documentation</a>.",
    href: null,
    stack: [
      "PHP",
      "TALL STACK",
      "Tailwind CSS",
      "Alpine JS",
      "Laravel 8",
      "Laravel Livewire",
      "Git",
      "Github",
      "CI/CD",
      "Heroku",
      "Excel Sheet Import",
    ],
  },
  {
    title: "Oyoyo",
    src: "https://drive.google.com/uc?id=11R763gUhnKkIGIaMHCao6FD5CRbb8RC-",
    description:
      "Oyoyo is an application built for tailors, weavers and other artisans for client management and work orders. Oyoyo aims to connect fashionistas to quality tailors and weavers by showcasing their works in a lookbook (a social feed inspired by tiktok) with ability to engage with artisans via liking, commenting or sharing their media post, as well as calling or chatting with registered tailors and weavers.",
    href: "https://oyoyo-staging.vercel.app",
    stack: [
      "React",
      "Redux",
      "Next JS",
      "Vercel",
      "SCSS",
      "CSS Grid",
      "FIGMA",
      "Git",
      "Gitlab",
      "CI/CD",
      "Node JS",
      "MongoDB",
      "Mongoose",
      "Socket IO",
      "Paystack Payments API",
    ],
  },
  {
    title: "Heroshe Website",
    src: "https://poly-screenshots.wellfound.com/Project/6f/1294385/b76d7133f7bb1eb9407ecb37334e59af-original.png",
    description:
      "Buy products from any trusted US online store using your Heroshe US Shipping Address and Heroshe will ship and deliver your package to you.",
    href: "https://heroshe.com",
    stack: [
      "Craft CMS",
      "Twig",
      "SCSS",
      "Git",
      "Docker",
      "Gitlab",
      "CI/CD",
      "Zeplin",
    ],
  },
  {
    title: "Heroshe Web Application",
    src: "https://poly-screenshots.wellfound.com/Project/7c/1294366/1927fd17f04da5f9047ee67efbf35937-original.png",
    description: "customer portal for Heroshe.",
    href: "https://myheroshe.com",
    stack: ["Nuxt JS", "SCSS", "Git", "Jest", "Gitlab", "CI/CD", "Zeplin"],
  },
  {
    title: "Tapword",
    src: "https://poly-screenshots.wellfound.com/Project/d9/1099006/1a74b806a76138f145f5fae5222a12be-original.png",
    description:
      "<em>words are limitless</em> : is a word game that tests your knowledge of English words. Tapword provides a means to combine as many letters as you can to make the longest word you possibly can when given a limited number of random letters..",
    href: "https://tapword.tunjioyeniran.com",
    stack: [
      "React",
      "Next JS",
      "SCSS",
      "CSS Grid",
      "Spellchecker Api",
      "Vercel",
      "PWA",
    ],
  },
  {
    title: "C & I Leasing Chatbot Forms",
    src: "https://poly-screenshots.wellfound.com/Project/36/1294386/6f505e609c16b9b5744b4270e2c0a86b-original.png",
    description:
      "webview forms developed for C & I Leasing Oracle ODA Chatbot. The forms are integrated with the client's car reservation API (test environment). <a href='https://c-ileasing-forms.vercel.app/reservation' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>Car Reservation Form</a>, <a href='https://c-ileasing-forms.vercel.app/dashboard' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>Hertz Feedback Form</a> and <a href='https://c-ileasing-forms.vercel.app/dashboard' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>Hertz Feedback Dashboard</a>. The forms are also designed to look like Google Forms.",
    href: "https://c-ileasing-forms.vercel.app",
    stack: [
      "React",
      "Next JS",
      "SCSS",
      "CSS Grid",
      "Git",
      "Gitlab",
      "CI/CD",
      "Node JS",
    ],
  },
  {
    title: "Homehealth",
    src: "https://poly-screenshots.wellfound.com/Project/db/1294384/e4106c3839aed7f982c2a8298a64e06c-original.png",
    description:
      "a portal that provides information about COVID-19 coronavirus. Resources, Statistics, <a href='https://homehealth.vercel.app/forms/risk-assessment' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>Risk Assessment Form</a> and <a href='https://homehealth.vercel.app/dashboard' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>Risk Assessment Dashboard</a>.",
    href: "https://homehealth.vercel.app",
    stack: [
      "React",
      "Next JS",
      "SCSS",
      "CSS Grid",
      "Git",
      "Gitlab",
      "CI/CD",
      "Node JS",
    ],
  },
  {
    title: "Trade Finance UI/UX Design",
    src: null,
    description:
      "UI/UX Design and Prototyping of a Trade Solution in progress ...",
    href: "https://www.figma.com/proto/kHXvT63ao4pzcCVX40fToq/Trade-Finance-Dashboard",
    stack: ["FIGMA", "Adobe Illustrator"],
  },
  {
    title: "Pepvote",
    src: "https://poly-screenshots.wellfound.com/Project/93/1099005/4e2581735fa68d71ee0ed1d5c7aa526b-original.png",
    description:
      "an electronic voting platform for managing elections, polls and other election processes.",
    href: "https://pepvote.com",
    stack: ["PHP", "Laravel", "Vue", "GitBook", "Bitbucket"],
  },
  {
    title: "Edgetechies",
    src: "https://poly-screenshots.wellfound.com/Project/83/1294380/9d4d56bf9ca58ad0855ba19559aabe9e-original.png",
    description:
      "Edgetechies, is a company passionate about designing & building compelling digital products, managing projects/brands and equipping everyday people/organizations to leverage new technologies in creating value.",
    href: "https://archive.edgetechies.com",
    stack: [
      "Vue",
      "Nuxt JS",
      "Netlify",
      "Netlify Forms",
      "SCSS",
      "CSS Grid",
      "Git",
      "Github",
      "CI/CD",
      "Node JS",
    ],
  },
  {
    title: "Alethic Resources",
    src: null,
    description: "official website of Alethic Resources Nigeria Limited.",
    href: "https://alethicresources.netlify.app",
    stack: ["React", "Bitbucket", "Netlify"],
  },
  {
    title: "Template String Parser",
    src: null,
    description:
      "a package for interpolating strings. replace parts of a template string with passed object key : value.",
    href: "https://github.com/tunjioye/templatestringparser",
    stack: ["JavaScript", "NPM"],
  },
  {
    title: "Sprocket API Frontend Demo",
    src: null,
    description:
      "Frontend Demo consuming API of a store of products with features such as filtering, sorting and pagination.",
    href: null,
    stack: ["React", "Next JS", "RSuite JS", "SCSS", "AJAX", "Heroku", "Git"],
  },
  {
    title: "Result Request System",
    src: null,
    description:
      "The Development of a System to Request Student Results from Universities. A Final Year Project Demo.",
    href: null,
    stack: [
      "PHP",
      "Laravel",
      "Vue",
      "AJAX",
      "Heroku",
      "PostgreSQL",
      "Git",
      "Github",
      "CI/CD",
    ],
  },
  {
    title: "Smart XMX",
    src: null,
    description:
      "Simple PHP Class to utilize <a href='https://smartsmssolutions.com' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>Smart SMS Solutions</a> Bulk SMS HTTP API.",
    href: "https://github.com/tunjioye/smartxmx",
    stack: ["CSS", "SCSS", "CSS Flex", "Git"],
  },
  {
    title: "Spectre CSS Examples",
    src: null,
    description:
      "Spectre CSS Examples provides some quick html examples based on the Spectre CSS Framework.",
    href: "https://github.com/tunjioye/spectre-css-examples",
    stack: ["CSS", "SCSS", "CSS Flex", "Git"],
  },
  {
    title: "TKP Mission Forms",
    src: null,
    description:
      "custom built form entry for TKP (The Kingdom Project) events and mission outreaches.",
    href: "https://forms.tkpmission.org",
    stack: ["Laravel", "Bootstrap 3", "Google Docs"],
  },
  {
    title: "TKP Forms API V1",
    src: null,
    description:
      "A collection of API Endpoints for TKP Mission Forms. Using <a href='https://jsonapi.org' target='_blank' rel='noopener noreferrer' class='text-blue-500 hover:underline underline-offset-4'>jsonapi</a> standard.",
    href: "https://documenter.getpostman.com/view/7841485/SzzoYukD",
    stack: ["Laravel", "JSON-API", "Postman"],
  },
  {
    title: "Brain on Mission",
    src: null,
    description: "built the brain on mission online goal card generator.",
    href: null,
    stack: ["Laravel", "jQuery", "AJAX"],
  },
  {
    title: "Studogram",
    src: null,
    description: "an affiliate online book store mainly for study materials.",
    href: null,
    stack: ["WordPress", "WooCommerce"],
  },
  {
    title: "Me",
    src: null,
    description:
      "build a simple portfolio just like mine : fork then change the preset configurations and markdown pages.",
    href: "https://tunji-oyeniran-portfolio.netlify.app",
    stack: ["React", "Gatsby", "GraphQL", "Markdown", "Github Pages", "PWA"],
  },
];
